In [1]:
# Import the dependencies.
import pandas as pd
import gmaps
import requests

# Import the API key.
from config import g_key

In [2]:
# Store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Sao Filipe,CV,2021-12-05 21:14:14,14.8961,-24.4956,297.48,72,71,5.34
1,1,Jishu,CN,2021-12-05 21:14:15,44.3167,126.8000,272.86,93,100,4.62
2,2,Avarua,CK,2021-12-05 21:14:15,-21.2078,-159.7750,300.18,89,40,2.57
3,3,Bambous Virieux,MU,2021-12-05 21:14:15,-20.3428,57.7575,298.83,78,40,3.60
4,4,Muros,ES,2021-12-05 21:14:15,42.7762,-9.0603,285.50,91,56,3.32

In [3]:
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

In [5]:
# 1. Assign the locations to an array of latitude and longitude pairs.
#locations = [latitude, longitude]
# 2. Assign the weights variable to some values.
#temperatures = # an array of length equal to the locations array length
# 3. Assign the figure variable to the gmaps.figure() attribute.
#fig = gmaps.figure()
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
#heatmap_layer = gmaps.heatmap_layer(locations, weights=temperatures)
# 5. Add the heatmap layer.
#fig.add_layer(heatmap_layer)
# 6. Call the figure to plot the data.
#fig



# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
temps = []
for temp in max_temp:
    temps.append(max(temp, 0))
#or using list comprehension: 
#temps = [max(temp, 0) for temp in max_temp]

In [7]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=temps)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable.
fig = gmaps.figure()
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [9]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable. add a zoom level so that only one map of Earth is shown.
fig = gmaps.figure(center=(7.0, 31.0), zoom_level=1.9)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp])
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [10]:
# Heatmap of temperature
# Get the latitude and longitude.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# Assign the figure variable. add a zoom level so that only one map of Earth is shown.
fig = gmaps.figure(center=(7.0, 31.0), zoom_level=1.9)
# Assign the heatmap variable.
heat_layer = gmaps.heatmap_layer(locations, weights=[max(temp, 0) for temp in max_temp], dissipating=False, max_intensity=300, point_radius=4)
# Add the heatmap layer.
fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [12]:
# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=clouds, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [13]:
# Heatmap of percent wind
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=wind, dissipating=False, max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [14]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 0
What is the maximum temperature you would like for your trip? 280

In [15]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
1,1,Jishu,CN,2021-12-05 21:14:15,44.3167,126.8000,272.86,93,100,4.62
8,8,Pevek,RU,2021-12-05 21:14:17,69.7008,170.3133,250.83,97,100,5.58
14,14,Oktyabrskiy,RU,2021-12-05 21:14:18,54.4815,53.4710,269.63,92,100,1.81
19,19,Ayan,RU,2021-12-05 21:14:19,56.4500,138.1667,267.48,65,99,1.89
26,26,Sistranda,NO,2021-12-05 21:10:42,63.7256,8.8340,268.09,69,75,6.74
28,28,Talnakh,RU,2021-12-05 21:14:20,69.4865,88.3972,244.93,99,100,6.22
30,30,Tiksi,RU,2021-12-05 21:14:21,71.6872,128.8694,247.34,91,100,2.94
32,32,Nikolskoye,RU,2021-12-05 21:14:21,59.7035,30.7861,255.38,97,9,2.15
34,34,Albany,US,2021-12-05 21:14:22,42.6001,-73.9662,277.91,54,96,2.01
36,36,Tuktoyaktuk,CA,2021-12-05 21:14:22,69.4541,-133.0374,245.15,76,40,3.09

In [16]:
preferred_cities_df.count()

City_ID       194
City          194
Country       194
Date          194
Lat           194
Lng           194
Max Temp      194
Humidity      194
Cloudiness    194
Wind Speed    194
dtype: int64

In [17]:
# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

           City Country  Max Temp      Lat       Lng Hotel Name
1         Jishu      CN    272.86  44.3167  126.8000
8         Pevek      RU    250.83  69.7008  170.3133
14  Oktyabrskiy      RU    269.63  54.4815   53.4710
19         Ayan      RU    267.48  56.4500  138.1667
26    Sistranda      NO    268.09  63.7256    8.8340
28      Talnakh      RU    244.93  69.4865   88.3972
30        Tiksi      RU    247.34  71.6872  128.8694
32   Nikolskoye      RU    255.38  59.7035   30.7861
34       Albany      US    277.91  42.6001  -73.9662
36  Tuktoyaktuk      CA    245.15  69.4541 -133.0374

In [18]:
# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [19]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]

IndexError: list index out of range

In [22]:
# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        #print('Hotel found')
    except (IndexError):
        print("Hotel not found... skipping.")

Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel not found... skipping.
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel not found... skipping.
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel not found... skipping.
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel found
Hotel not found... skipping.
Hotel found
Hotel found

In [48]:
hotel_df.head(10)

           City Country  Max Temp      Lat       Lng               Hotel Name
1         Jishu      CN    272.86  44.3167  126.8000     Xinjia Fashion Hotel
8         Pevek      RU    250.83  69.7008  170.3133         Severnoye Zoloto
14  Oktyabrskiy      RU    269.63  54.4815   53.4710       Уязы-Тау гостиница
19         Ayan      RU    267.48  56.4500  138.1667               Gostinitsa
26    Sistranda      NO    268.09  63.7256    8.8340             Hotell Frøya
28      Talnakh      RU    244.93  69.4865   88.3972            Talnakh Hotel
30        Tiksi      RU    247.34  71.6872  128.8694                  Arktika
32   Nikolskoye      RU    255.38  59.7035   30.7861  Tourist House - Sablino
34       Albany      US    277.91  42.6001  -73.9662
36  Tuktoyaktuk      CA    245.15  69.4541 -133.0374     End of The Road Ltd.

In [73]:
import numpy as np

#hotel_df['Hotel Name'].astype(str).apply(lambda x: x.strip()).replace('', np.nan)

hotel_df.loc[hotel_df['Hotel Name']==''] = np.nan

hotel_df.dropna(inplace=True)
hotel_df.head(10)

,City,Country,Max Temp,Lat,Lng,Hotel Name
1,Jishu,CN,272.86,44.3167,126.8000,Xinjia Fashion Hotel
8,Pevek,RU,250.83,69.7008,170.3133,Severnoye Zoloto
14,Oktyabrskiy,RU,269.63,54.4815,53.4710,Уязы-Тау гостиница
19,Ayan,RU,267.48,56.4500,138.1667,Gostinitsa
26,Sistranda,NO,268.09,63.7256,8.8340,Hotell Frøya
28,Talnakh,RU,244.93,69.4865,88.3972,Talnakh Hotel
30,Tiksi,RU,247.34,71.6872,128.8694,Arktika
32,Nikolskoye,RU,255.38,59.7035,30.7861,Tourist House - Sablino
36,Tuktoyaktuk,CA,245.15,69.4541,-133.0374,End of The Road Ltd.
38,Kushiro,JP,274.22,42.9750,144.3747,Toyoko Inn Kushiro Jujigai

In [74]:
# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

In [ ]:
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [ ]:
print(hotel_info)

In [ ]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig