## Deliverable 2. Create a Customer Travel Destinations Map.

In [83]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps API key
gmaps.configure(api_key=g_key)

import numpy as np
from datetime import datetime
import time

In [84]:
# 1. Import the WeatherPy_database.csv file. 
city_data_df = pd.read_csv('../Weather_Database/WeatherPy_database.csv')
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
0,0,Busselton,AU,2021-12-09 05:49:33,-33.6500,115.3333,310.40,54,38,5.60,scattered clouds
1,1,Alihe,CN,2021-12-09 05:49:34,50.5667,123.7167,270.60,81,100,1.79,overcast clouds
2,2,Severodvinsk,RU,2021-12-09 05:49:36,64.5635,39.8302,257.21,95,98,1.83,overcast clouds
3,3,Lebu,CL,2021-12-09 05:49:37,-37.6167,-73.6500,286.10,91,3,7.14,clear sky
4,4,Bogatyye Saby,RU,2021-12-09 05:49:39,56.0102,50.4483,269.31,95,100,4.58,overcast clouds

In [85]:
# 2. Prompt the user to enter minimum and maximum temperature criteria 
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 0
What is the maximum temperature you would like for your trip? 290

In [86]:
# 3. Filter the city_data_df DataFrame using the input statements to create a new DataFrame using the loc method.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
1,1,Alihe,CN,2021-12-09 05:49:34,50.5667,123.7167,270.60,81,100,1.79,overcast clouds
2,2,Severodvinsk,RU,2021-12-09 05:49:36,64.5635,39.8302,257.21,95,98,1.83,overcast clouds
3,3,Lebu,CL,2021-12-09 05:49:37,-37.6167,-73.6500,286.10,91,3,7.14,clear sky
4,4,Bogatyye Saby,RU,2021-12-09 05:49:39,56.0102,50.4483,269.31,95,100,4.58,overcast clouds
5,5,Izumo,JP,2021-12-09 05:49:41,35.3667,132.7667,288.12,58,40,4.63,scattered clouds
6,6,Adrar,MR,2021-12-09 05:49:42,20.5022,-10.0711,286.93,19,82,4.49,broken clouds
7,7,Orange Cove,US,2021-12-09 05:49:43,36.6244,-119.3137,286.40,62,70,0.97,broken clouds
8,8,Bluff,NZ,2021-12-09 05:49:44,-46.6000,168.3333,286.37,67,94,6.74,overcast clouds
9,9,Provideniya,RU,2021-12-09 05:49:46,64.3833,-173.3000,255.62,98,100,8.01,light snow
14,14,Mataura,NZ,2021-12-09 05:49:52,-46.1927,168.8643,286.19,87,99,2.02,overcast clouds

In [87]:
preferred_cities_df.head(50)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed,Weather Description
1,1,Alihe,CN,2021-12-09 05:49:34,50.5667,123.7167,270.60,81,100,1.79,overcast clouds
2,2,Severodvinsk,RU,2021-12-09 05:49:36,64.5635,39.8302,257.21,95,98,1.83,overcast clouds
3,3,Lebu,CL,2021-12-09 05:49:37,-37.6167,-73.6500,286.10,91,3,7.14,clear sky
4,4,Bogatyye Saby,RU,2021-12-09 05:49:39,56.0102,50.4483,269.31,95,100,4.58,overcast clouds
5,5,Izumo,JP,2021-12-09 05:49:41,35.3667,132.7667,288.12,58,40,4.63,scattered clouds
6,6,Adrar,MR,2021-12-09 05:49:42,20.5022,-10.0711,286.93,19,82,4.49,broken clouds
7,7,Orange Cove,US,2021-12-09 05:49:43,36.6244,-119.3137,286.40,62,70,0.97,broken clouds
8,8,Bluff,NZ,2021-12-09 05:49:44,-46.6000,168.3333,286.37,67,94,6.74,overcast clouds
9,9,Provideniya,RU,2021-12-09 05:49:46,64.3833,-173.3000,255.62,98,100,8.01,light snow
14,14,Mataura,NZ,2021-12-09 05:49:52,-46.1927,168.8643,286.19,87,99,2.02,overcast clouds
15,15,Wajima,JP,2021-12-09 05:49:53,37.4000,136.9000,286.53,58,40,4.12,scattered clouds
16,16,Ushuaia,AR,2021-12-09 05:49:55,-54.8000,-68.3000,285.96,50,20,4.63,few clouds
18,18,Nanortalik,GL,2021-12-09 05:49:57,60.1432,-45.2371,272.54,88,67,9.02,broken clouds
21,21,Wladyslawowo,PL,2021-12-09 05:50:01,54.7909,18.4009,269.78,73,100,9.69,overcast clouds
23,23,Sisimiut,GL,2021-12-09 05:50:04,66.9395,-53.6735,265.29,66,100,2.89,overcast clouds
28,28,Kamen-Rybolov,RU,2021-12-09 05:50:13,44.7481,132.0403,272.90,88,81,3.98,broken clouds
32,32,Hasaki,JP,2021-12-09 05:50:18,35.7333,140.8333,285.53,65,98,11.35,overcast clouds
33,33,Chuy,UY,2021-12-09 05:50:20,-33.6971,-53.4616,289.03,83,64,3.17,broken clouds
34,34,Gimli,CA,2021-12-09 05:50:22,50.6336,-96.9907,266.72,79,100,10.80,overcast clouds
35,35,Mugla,TR,2021-12-09 05:50:23,37.2303,28.3557,273.52,69,3,0.58,clear sky
37,37,Tuktoyaktuk,CA,2021-12-09 05:50:26,69.4541,-133.0374,260.15,85,90,5.66,light snow
39,39,Rabo De Peixe,PT,2021-12-09 05:50:29,37.8000,-25.5833,287.75,96,40,2.57,scattered clouds
42,42,Punta Arenas,CL,2021-12-09 05:50:35,-53.1500,-70.9167,283.21,71,0,3.09,clear sky
43,43,Norman Wells,CA,2021-12-09 05:50:37,65.2820,-126.8329,265.17,79,90,8.23,light snow
44,44,Jamestown,US,2021-12-09 05:50:38,42.0970,-79.2353,271.92,89,90,1.34,light snow
50,50,Albany,US,2021-12-09 05:50:45,42.6001,-73.9662,272.25,87,93,0.45,overcast clouds
54,54,Half Moon Bay,US,2021-12-09 05:50:51,37.4636,-122.4286,285.72,93,90,4.12,overcast clouds
56,56,Severo-Kurilsk,RU,2021-12-09 05:50:53,50.6789,156.1250,274.03,75,74,11.28,broken clouds
57,57,Khatanga,RU,2021-12-09 05:50:55,71.9667,102.5000,254.49,97,100,3.44,overcast clouds
58,58,Upernavik,GL,2021-12-09 05:50:56,72.7868,-56.1549,262.33,93,100,4.62,overcast clouds
61,61,Kodiak,US,2021-12-09 05:51:01,57.7900,-152.4072,274.88,48,1,1.54,clear sky
64,64,Barrow,US,2021-12-09 05:51:05,71.2906,-156.7887,257.16,85,90,10.29,light snow
65,65,Homer,US,2021-12-09 05:51:06,59.6425,-151.5483,274.09,64,90,5.14,overcast clouds
67,67,Kvarkeno,RU,2021-12-09 05:51:09,52.0833,59.7250,261.74,76,100,3.41,overcast clouds
68,68,San Lawrenz,MT,2021-12-09 05:51:11,36.0553,14.2040,287.82,82,11,0.89,few clouds
69,69,Nuuk,GL,2021-12-09 05:51:12,64.1835,-51.7216,262.81,80,100,2.59,overcast clouds
70,70,Aklavik,CA,2021-12-09 05:51:13,68.2191,-135.0107,259.61,94,100,0.84,overcast clouds
71,71,Bethel,US,2021-12-09 05:51:16,41.3712,-73.4140,274.11,86,93,2.54,overcast clouds
74,74,Kaitangata,NZ,2021-12-09 05:51:20,-46.2817,169.8464,288.11,79,100,3.40,overcast clouds
76,76,Torbat-E Jam,IR,2021-12-09 05:51:22,35.2440,60.6225,284.87,30,0,2.01,clear sky
78,78,Hamilton,US,2021-12-09 05:51:25,39.1834,-84.5333,271.72,88,1,1.54,clear sky
81,81,Clinton,US,2021-12-09 05:51:29,42.5870,-82.9199,273.09,78,75,0.45,broken clouds
82,82,Muyezerskiy,RU,2021-12-09 05:51:30,63.9333,31.6500,258.24,98,88,1.65,overcast clouds
84,84,Smithers,CA,2021-12-09 05:50:33,54.7804,-127.1743,264.33,92,90,2.06,overcast clouds
85,85,Korla,CN,2021-12-09 05:50:12,41.7597,86.1469,274.35,39,100,1.25,overcast clouds
86,86,Qasigiannguit,GL,2021-12-09 05:51:35,68.8193,-51.1922,263.13,67,100,3.35,overcast clouds
88,88,Pacific Grove,US,2021-12-09 05:51:37,36.6177,-121.9166,285.97,92,90,0.45,overcast clouds
89,89,Chokurdakh,RU,2021-12-09 05:51:39,70.6333,147.9167,228.30,100,97,1.49,overcast clouds
93,93,Cabra,ES,2021-12-09 05:51:45,37.4725,-4.4421,282.81,88,35,1.15,scattered clouds
98,98,Los Llanos De Aridane,ES,2021-12-09 05:51:51,28.6585,-17.9182,289.89,77,75,4.02,mist

In [88]:
preferred_cities_df.count()

City_ID                1120
City                   1120
Country                1118
Date                   1120
Lat                    1120
Lng                    1120
Max Temp               1120
Humidity               1120
Cloudiness             1120
Wind Speed             1120
Weather Description    1120
dtype: int64

In [89]:
# 4a. Determine if there are any empty rows.
preferred_cities_df.isna().sum()

City_ID                0
City                   0
Country                2
Date                   0
Lat                    0
Lng                    0
Max Temp               0
Humidity               0
Cloudiness             0
Wind Speed             0
Weather Description    0
dtype: int64

In [90]:
# 4b. Drop any empty rows and create a new DataFrame that doesn’t have empty rows.
clean_df = preferred_cities_df.dropna()

In [91]:
# 5a. Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = clean_df[["City", "Country", "Max Temp", "Weather Description", "Lat", "Lng"]].copy()

#rename "Weather Description" to 'Current Description' following template
hotel_df.rename(columns={'Weather Description': 'Current Description'}, inplace=True)

# 5b. Create a new column "Hotel Name"
hotel_df["Hotel Name"] = ""

hotel_df.head()

,City,Country,Max Temp,Current Description,Lat,Lng,Hotel Name
1,Alihe,CN,270.60,overcast clouds,50.5667,123.7167,
2,Severodvinsk,RU,257.21,overcast clouds,64.5635,39.8302,
3,Lebu,CL,286.10,clear sky,-37.6167,-73.6500,
4,Bogatyye Saby,RU,269.31,overcast clouds,56.0102,50.4483,
5,Izumo,JP,288.12,scattered clouds,35.3667,132.7667,

In [92]:
hotel_df.count()

City                   1118
Country                1118
Max Temp               1118
Current Description    1118
Lat                    1118
Lng                    1118
Hotel Name             1118
dtype: int64

In [93]:
# 6a. Set parameters to search for hotels with 5000 meters.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}
    
# 6b. Iterate through the hotel DataFrame.    
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # 6c. Get latitude and longitude from DataFrame
    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # 6d. Set up the base URL for the Google Directions API to get JSON data.
    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    
    # 6e. Make request and retrieve the JSON data from the search. 
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    
    # 6f. Get the first hotel from the results and store the name, if a hotel isn't found skip the city.
    # Grab the first hotel from the results and store the name.
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
        #print('Hotel found')
    except (IndexError):
        print("Hotel not found... skipping.")
        #hotel_df.loc[index, "Hotel Name"] = np.nan

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [94]:
# 7. Drop the rows where there is no Hotel Name.

#hotel_df['Hotel Name'].astype(str).apply(lambda x: x.strip()).replace('', np.nan)

hotel_df.loc[hotel_df['Hotel Name']==''] = np.nan

#hotel_df.dropna(inplace=True)
clean_hotel_df = hotel_df.dropna()

clean_hotel_df.count()

City                   959
Country                959
Max Temp               959
Current Description    959
Lat                    959
Lng                    959
Hotel Name             959
dtype: int64

In [95]:
# 8a. Create the output File (CSV)
output_data_file='WeatherPy_vacation.csv'

# 8b. Export the City_Data into a csv
clean_hotel_df.to_csv(output_data_file, index_label="City_ID")

In [96]:
# 9. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Current Description</dt><dd>{Current Description}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# 10a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in clean_hotel_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = clean_hotel_df[["Lat", "Lng"]]

In [97]:
# 11a. Add a marker layer for each city to the map. 
max_temp = clean_hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# 11b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))